name: CI

on:
  push:
    branches:
    - use-tree-sitter
  pull_request:
    branches:
    - use-tree-sitter
  schedule:
    - cron:  '31 1 * * *'

jobs:
  ubuntu-tcc:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      VFLAGS: -cc tcc
    steps:
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - uses: actions/checkout@v2
      with:
        path: vls
        ref: use-tree-sitter
    - name: Clone tree-sitter-v to ~/.vmodules/tree_sitter_v
      run: git clone --depth 1 https://github.com/nedpals/tree-sitter-v ~/.vmodules/tree_sitter_v
    - name: Build local v
      run: make -j4
    - name: Run tests
      run: ./v test vls

  macos-clang:
    runs-on: macOS-latest
    timeout-minutes: 30
    env:
      VFLAGS: -cc clang
    steps:
    - name: Checkout V
      uses: actions/checkout@v2
      with:
        repository: vlang/v
    - uses: actions/checkout@v2
      with:
        path: vls
        ref: use-tree-sitter
    - name: Clone tree-sitter-v to ~/.vmodules/tree_sitter_v
      run: git clone --depth 1 https://github.com/nedpals/tree-sitter-v ~/.vmodules/tree_sitter_v
    - name: Build local v
      run: make -j4
    - name: Run tests
      run: ./v test vls

  # windows-msvc:
  #   runs-on: windows-2019
  #   timeout-minutes: 30
  #   env:
  #       VFLAGS: -cc msvc
  #   steps:
  #   - name: Checkout V
  #     uses: actions/checkout@v2
  #     with:
  #       repository: vlang/v
  #   - uses: actions/checkout@v2
  #     with:
  #       path: vls
  #   - name: Build local v
  #     run: .\make.bat -msvc
  #   - name: Run tests
  #     run: .\v.exe test vls
